/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sampleapp;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.LinkedList;

public class AppTest {
}
